export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/share/npm/bin:$PATH"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="./bin:$PATH"
export MANPATH="/usr/share/man:/usr/local/share/man"
export GOPATH="$HOME/go"

export PATH="/usr/local/opt/node@0.12/bin:$PATH"
